image: node:lts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DEV_DOMAIN: static-website-2024-dev.surge.sh
  STAGING_DOMAIN: static-website-2024-staging.surge.sh
  PRODUCTION_DOMAIN: static-website-2024-production.surge.sh  

stages:
  - build
  - test-build
  - deploy-dev
  - test-dev
  - deploy-staging
  - test-staging
  - deploy-production
  - test-production

.deploy_template:
  environment:
    name: $ENVIRONMENT
    url: $DOMAIN
  script:
    - npm install -g surge
    - surge --project ./public --domain $DOMAIN

build webiste:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test-build
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test-build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 5
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy website in dev:
  stage: deploy
  <<: *deploy

test website in dev: