stages:
  - terraform
  - check_file
  - write_to_file

Install Terraform:
  stage: terraform
  script:
    - echo "Starting Installation..."
    - apt-get update && apt-get install -y gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update
    - apt-get install terraform
    - terraform init
    - terraform validate
    - terraform fmt
    - terraform plan -out planfile
    - test -f planfile
    - terraform apply -auto-approve planfile
  artifacts:
    paths:
      - testFile

Check File:
  stage: check_file
  script:
    - test -f testFile
    - cat testFile

Write to File:
  stage: write_to_file
  script:
    - echo "1...2...3" >> testFile
    - cat testFile